CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.sniggie.fun
USER_HOST: user.backend-alb-{{ env }}.sniggie.fun
CART_HOST: cart.backend-alb-{{ env }}.sniggie.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.sniggie.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.sniggie.fun
