- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from : app-setup.yaml 

#  Added this as part of latest python3 from repos have upgraded openssl-libs but other openssl packages are old in AMI, so mismatch occured.
# - name: upgrade openssl packages
#   ansible.builtin.dnf:
#     name: "{{ item }}"
#     state: latest
#   loop:
#   - openssl
#   - openssl-libs
#   - openssh
#   - openssh-server
#   - openssh-clients

- name: Install python and requirements
  ansible.builtin.import_role:
    name: common
    tasks_from : python.yaml


- name: System setup
  ansible.builtin.import_role:
    name: common
    tasks_from : system-setup.yaml
