- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: install python libraries
  ansible.builtin.pip:
    name:
      - botocore
      - boto3
    state: present


- name: enable and start mysql server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true

- name: setup mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASS }}
